name: demo-app
infra:
  provider: bicep
services:
  api:
    project: ./src/api
    language: python
    host: appservice
  # func:
  #   project: ./src/func
  #   language: python
  #   host: function
  mcp:
    project: ./src/mcp
    language: python
    host: function
pipeline:
  variables:
    - AZURE_APPSERVICEPLAN_NAME
    - AZURE_APPSERVICEPLAN_RG
    - AZURE_COSMOSDB_NAME
    - AZURE_COSMOSDB_RG
    - AZURE_KEYVAULT_NAME
    - AZURE_KEYVAULT_RG
    - COSMOS_DB_DATABASE_NAME
    - AZURE_AI_SEARCH_SERVICE_NAME
