name: demo-app
infra:
  provider: bicep
services:
  func:
    project: ./src/func
    dist: .azure/dist
    language: python
    host: function
pipeline:
  variables:
    - AZURE_COSMOSDB_NAME
    - AZURE_COSMOSDB_RG
    - AZURE_KEYVAULT_NAME
    - AZURE_KEYVAULT_RG
