name: Test API

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "src/api/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python version
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.5.13"

      - name: Setup Socket Firewall
        uses: socketdev/action@937f824ec476dfd164d4a4d9995751427b0be143 # v1
        with:
          mode: firewall

      - name: Install dependencies
        run: |
          cd src/api
          sfw uv sync

      - name: Run Ruff check
        run: |
          cd src/api
          uv run ruff check .

      - name: Run Ruff format check
        run: |
          cd src/api
          uv run ruff format --check .

      - name: Run tests
        run: |
          cd src/api
          uv run pytest -s
